language: csharp
solution: TorrentDelivery.sln

sudo: false

addons:
  apt:
    packages:
      - nunit-console
      
install:
  - nuget restore TorrentDelivery.sln

script:
  - xbuild TorrentDelivery.sln
